import astropy.units as u
from astropy.io import ascii
import ephem
from numpy import *
import string
import sys
import astropy.coordinates as coord
import astropy.units as u


catname="nuvtest.dat"
tdata=ascii.read(catname)


objname=tdata['obj']
ra=tdata['ra']
dec=tdata['dec']

rad=coord.Angle(ra,unit=u.hour)
radd=rad.degree
radh=rad.hour
decd=coord.Angle(dec,unit=u.deg)
decdd=decd.degree


afopt='#autofocus'
skipopt='#skippreviews'
expopt='#express'
countopt='#count 3'
intopt='#interval 180'
binopt='#binning 1'
filteropt='#filter R'
head1=';\n'
head2='; Single target image series plan, created by Changsu Choi on Thu, 27 Nov 2014 06:24:30 UTC\n'
head3='; NOT Generated by iTelescope.Net Offline Plan Generator, generated by python code (C.C.)\n'
head4=';\n'


for obj in objname :
	f=open(objname+'base.txt','w')
	f.write(head1,head2,head3,head4)
	f.write(afopt)
	f.write(skipopt)
	f.write(expopt)
	f.write(intopt)
	f.write(binopt)
	f.write(filteropt)
	f.write(objname,' ',str(radh),' ',str(decdd))
	f.write('\n')
	


	f.close()	



